=== Justinio99/graviton/src/Graviton/GeneratorBundle/Resources/schema/definition-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "JSON definition schema",
  "description": "Schema for JSON definition validation",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-zA-Z_][a-zA-Z0-9_]*$"
    },
    "isSubDocument": {
      "type": "boolean"
    },
    "description": {
      "type": "string"
    },
    "service": {
      "type": "object"
    },
    "target": {
      "type": "object"
    }
  },
  "required": [
    "id",
    "target"
  ],
  "additionalProperties": false
}

=== Justinio99/graviton/src/Graviton/CoreBundle/Resources/definition/Version.json
{
  "id": "Version",
  "description": "Returns the version number of the installed packages",
  "service": {
    "readOnly": true,
    "routerBase": "/core/version/",
    "parent": "graviton.core.controller.version",
    "baseController": "\\Graviton\\CoreBundle\\Controller\\VersionController"
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "version",
        "type": "varchar",
        "title": "version",
        "description": "version numbers of packages"
      }
    ]
  }
}

=== Justinio99/graviton/src/Graviton/CoreBundle/Resources/definition/Versions.json
{
  "id": "Version",
  "description": "Returns the version number of the installed packages",
  "service": {
    "readOnly": true,
    "routerBase": "/core/version/",
    "parent": "graviton.core.controller.version",
    "baseController": "\\Graviton\\CoreBundle\\Controller\\VersionController",
    "fixtures": [
      {
        "id" : "graviton",
        "version": "0.23.1"
      }
    ]
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "id",
        "type": "varchar",
        "title": "ID",
        "description": "Unique identifier."
      },
      {
        "name": "version",
        "type": "varchar",
        "title": "version",
        "description": "version number of package"
      }
    ]
  }
}

=== Justinio99/graviton/src/Graviton/SwaggerBundle/Resources/definition/versions.json
{
  "id": "Version",
  "description": "Returns the version number of the installed packages",
  "service": {
    "readOnly": true,
    "routerBase": "/core/version/",
    "parent": "graviton.swagger.controller.version",
    "baseController": "\\Graviton\\SwaggerBundle\\Controller\\SwaggerController"
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "versions",
        "type": "object",
        "title": "versions",
        "description": "holds package version numbers"
      }
    ]
  }
}

=== Justinio99/graviton/src/Graviton/RabbitMqBundle/Resources/definition/EventStatus.json
{
  "id": "EventStatus",
  "description": "A service providing resources providing status' on events subscribed by workers.",
  "service": {
    "readOnly": false,
    "routerBase": "/event/status/"
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "id",
        "type": "varchar",
        "title": "ID",
        "description": "Unique identifier"
      },
      {
        "name": "createDate",
        "type": "datetime",
        "title": "Creation date",
        "description": "Creation date",
        "readOnly": true
      },
      {
        "name": "status.0.workerId",
        "type": "string",
        "title": "Worker ID",
        "description": "ID of a worker",
        "required": true
      },
      {
        "name": "status.0.status",
        "type": "string",
        "title": "Status",
        "description": "A string representing the status (opened, working, failed, done)",
        "required": true
      },
      {
        "name": "errorInformation.0.workerId",
        "type": "string",
        "title": "Worker ID",
        "description": "ID of a worker"
      },
      {
        "name": "errorInformation.0.content",
        "type": "string",
        "title": "Error output",
        "description": "A place where a worker can put error information"
      }
    ]
  }
}

=== Justinio99/graviton/src/Graviton/RabbitMqBundle/Resources/definition/QueueEvent.json
{
  "id": "QueueEvent",
  "description": "An object serving as model on what we send to our message queue",
  "service": {
    "readOnly": false,
    "routerBase": null
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "id",
        "type": "varchar",
        "title": "ID",
        "description": "Unique identifier"
      },
      {
        "name": "className",
        "type": "varchar",
        "title": "Class name",
        "description": "The class name the events concerns"
      },
      {
        "name": "recordId",
        "type": "varchar",
        "title": "Record ID",
        "description": "The ID of the affected record"
      },
      {
        "name": "event",
        "type": "varchar",
        "title": "Event",
        "description": "The event that happened (create, update, delete)"
      },
      {
        "name": "publicUrl",
        "type": "varchar",
        "title": "Public URL",
        "description": "An optional URL from which the affected resource can be fetched."
      }
    ]
  }
}

=== Justinio99/graviton/src/Graviton/CoreBundle/Resources/definition/Module.json
{
    "id": "Module",
    "description": "A service containing modules that relate to apps",
    "service": {
        "readOnly": false,
        "routerBase": "/configuration/module/",
        "fixtures": []
    },
    "target": {
        "indexes": [],
        "relations": [],
        "fields": [
            {
                "name": "id",
                "type": "varchar",
                "title": "ID",
                "description": "Unique identifier for an item."
            },
            {
                "name": "appId",
                "type": "varchar",
                "title": "App ID",
                "description": "ID of an app this module relates to.",
                "required": true
            },
            {
                "name": "name",
                "type": "varchar",
                "title": "Name",
                "description": "Name of this module",
                "required": true,
                "translatable": true
            },
            {
                "name": "path",
                "type": "varchar",
                "title": "Path",
                "description": "A path this module points to.",
                "translatable": false
            },
            {
                "name": "order",
                "type": "int",
                "title": "Order",
                "description": "Integer for sort order"
            }
        ]
    }
}

=== Justinio99/graviton/src/Graviton/FileBundle/Resources/definition/File.json
{
  "id": "File",
  "description": "File storage service",
  "service": {
    "readOnly": false,
    "routerBase": "/file/",
    "baseController": "\\Graviton\\FileBundle\\Controller\\FileController",
    "parent": "graviton.file.controller.file",
    "fixtures": [
      {
      }    
    ]
  },
  "target": {
    "indexes": [],
    "relations": [],
    "fields": [
      {
        "name": "id",
        "type": "varchar",
        "title": "ID",
        "description": "Unique file identifier."
      },
      {
        "name": "links.0.ref",
        "type": "extref",
        "title": "Link",
        "description": "Link to any document.",
        "exposeAs": "$ref"
      }
    ]
  }
}

=== Justinio99/graviton/resources/definition/Showcase.json
{
    "id": "Showcase",
    "description": "A service showcasing all of our generator features",
    "service": {
        "readOnly": false,
        "baseController": "\\Graviton\\CoreBundle\\Controller\\ShowcaseExtensionController",
        "routerBase": "/hans/showcase/",
        "fixtures": {
            "": [
                {
                    "id": 5,
                    "anotherInt": 655,
                    "testField": {"en": "a string value"},
                    "someOtherField": {"en": "some ol' string"},
                    "aBoolean": false,
                    "modificationDate": "1984-05-02T00:00:00Z"
                }
            ],
            "contactCode": [
                {
                    "someDate": "1979-12-21T00:00:00Z",
                    "text": {"en": "Dudi"}
                }
            ]
        }
    },
    "target": {
        "indexes": [],
        "relations": [],
        "fields": [
            {
                "name": "id",
                "type": "INT",
                "description": "Unique identifier for an item."
            },
            {
                "name": "anotherInt",
                "type": "INT",
                "description": "Just a nice integer",
                "required": true
            },
            {
                "name": "testField",
                "type": "varchar",
                "title": "A testing title",
                "description": "A lengthy and detailed description.",
                "required": true,
                "translatable": true
            },
            {
                "name": "someOtherField",
                "type": "varchar",
                "title": "Another field",
                "description": "A very nice field",
                "translatable": true
            },
            {
                "name": "aBoolean",
                "type": "boolean",
                "title": "Some boolean",
                "description": "Everybody likes a good ol' bool",
                "required": true
            },
            {
                "name": "modificationDate",
                "type": "datetime",
                "title": "An important date",
                "description": "Don't forget to save the date"
            },
            {
                "name": "contact",
                "type": "class:Graviton\\PersonBundle\\Document\\PersonContact",
                "title": "A single contact element",
                "description": "How to contact someone..",
                "required": false
            },
            {
                "name": "contacts",
                "type": "class:Graviton\\PersonBundle\\Document\\PersonContact[]",
                "title": "An array of contact elements..",
                "description": "Other ways to contact someone.."
            },
            {
                "name": "contactCode.someDate",
                "type": "datetime",
                "title": "Another datetime",
                "description": "Who doesn't like a datetime??"
            },
            {
                "name": "contactCode.text",
                "type": "varchar",
                "translatable": true,
                "required": true,
                "title": "Meaning of the code",
                "description": "Some text to the code.."
            },
            {
                "name": "nestedArray.0.name",
                "type": "varchar",
                "title": "Name of nested array",
                "description": "Some text"
            }
        ]
    }
}
