=== Justinio99/graviton/src/Graviton/GeneratorBundle/Resources/schema/definition-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "JSON definition schema",
  "description": "Schema for JSON definition validation",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-zA-Z_][a-zA-Z0-9_]*$"
    },
    "isSubDocument": {
      "type": "boolean"
    },
    "description": {
      "type": "string"
    },
    "service": {
      "type": "object"
    },
    "target": {
      "type": "object"
    }
  },
  "required": [
    "id",
    "target"
  ],
  "additionalProperties": false
}

=== Justinio99/graviton/src/Graviton/CoreBundle/Resources/definition/App.json
{
    "id": "App",
    "description": "A graviton based app.",
    "service": {
        "readOnly": false,
        "routerBase": "/core/app/",
        "fixtures": []
    },
    "target": {
        "indexes": [
          "key",
          "default",
          "value"
        ],
        "relations": [],
        "fields": [
            {
                "name": "id",
                "type": "varchar",
                "title": "ID",
                "description": "Unique identifier",
                "required": true
            },
            {
                "name": "name",
                "type": "varchar",
                "title": "Name",
                "description": "Display name for an app.",
                "required": true,
                "translatable": true
            },
            {
                "name": "showInMenu",
                "type": "boolean",
                "title": "Show in Menu",
                "description": "Define if an app should be exposed on the top level menu.",
                "required": true
            },
            {
                "name": "order",
                "type": "int",
                "title": "Order",
                "description": "Order sorting field"
            }
        ]
    }
}
